# Generated by Django 3.2.21 on 2023-12-04 00:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ean', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='O Ean deve conter 13 caracteres', regex='^.{13}$')], verbose_name='EAN')),
                ('name', models.TextField(verbose_name='Nome do Produto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagens', verbose_name='Imagem do produto')),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço mínimo')),
                ('max_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço máximo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Preço (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='api.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Produto - Configuração de preço',
                'verbose_name_plural': 'Produtos - Configurações de preço',
            },
        ),
    ]
